/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripDetailsReportRouteImport } from './routes/trip-details-report'
import { Route as SuggestedPayReportRouteImport } from './routes/suggested-pay-report'
import { Route as IndexRouteImport } from './routes/index'

const TripDetailsReportRoute = TripDetailsReportRouteImport.update({
  id: '/trip-details-report',
  path: '/trip-details-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestedPayReportRoute = SuggestedPayReportRouteImport.update({
  id: '/suggested-pay-report',
  path: '/suggested-pay-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/suggested-pay-report': typeof SuggestedPayReportRoute
  '/trip-details-report': typeof TripDetailsReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/suggested-pay-report': typeof SuggestedPayReportRoute
  '/trip-details-report': typeof TripDetailsReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/suggested-pay-report': typeof SuggestedPayReportRoute
  '/trip-details-report': typeof TripDetailsReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/suggested-pay-report' | '/trip-details-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/suggested-pay-report' | '/trip-details-report'
  id: '__root__' | '/' | '/suggested-pay-report' | '/trip-details-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuggestedPayReportRoute: typeof SuggestedPayReportRoute
  TripDetailsReportRoute: typeof TripDetailsReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-details-report': {
      id: '/trip-details-report'
      path: '/trip-details-report'
      fullPath: '/trip-details-report'
      preLoaderRoute: typeof TripDetailsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggested-pay-report': {
      id: '/suggested-pay-report'
      path: '/suggested-pay-report'
      fullPath: '/suggested-pay-report'
      preLoaderRoute: typeof SuggestedPayReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuggestedPayReportRoute: SuggestedPayReportRoute,
  TripDetailsReportRoute: TripDetailsReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
